CREATE TABLE "CAATDemo".customers (
  customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  "NAME" VARCHAR2(255 BYTE) NOT NULL,
  address VARCHAR2(255 BYTE),
  website VARCHAR2(255 BYTE),
  credit_limit NUMBER(8,2),
  PRIMARY KEY (customer_id)
);