CREATE TABLE "CAATDemo".locations (
  location_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  address VARCHAR2(255 BYTE) NOT NULL,
  postal_code VARCHAR2(20 BYTE),
  city VARCHAR2(50 BYTE),
  "STATE" VARCHAR2(50 BYTE),
  country_id CHAR(2 BYTE),
  PRIMARY KEY (location_id),
  CONSTRAINT fk_locations_countries FOREIGN KEY (country_id) REFERENCES "CAATDemo".countries (country_id) ON DELETE CASCADE
);