CREATE TABLE "CAATDemo".orders (
  order_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  customer_id NUMBER(6) NOT NULL,
  status VARCHAR2(20 BYTE) NOT NULL,
  salesman_id NUMBER(6),
  order_date DATE NOT NULL,
  PRIMARY KEY (order_id),
  CONSTRAINT fk_orders_customers FOREIGN KEY (customer_id) REFERENCES "CAATDemo".customers (customer_id) ON DELETE CASCADE,
  CONSTRAINT fk_orders_employees FOREIGN KEY (salesman_id) REFERENCES "CAATDemo".employees (employee_id) ON DELETE SET NULL
);