CREATE TABLE "RedGate".products (
  product_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  product_name VARCHAR2(255 BYTE) NOT NULL,
  description VARCHAR2(2000 BYTE),
  standard_cost NUMBER(9,2),
  list_price NUMBER(9,2),
  category_id NUMBER NOT NULL,
  PRIMARY KEY (product_id),
  CONSTRAINT fk_products_categories FOREIGN KEY (category_id) REFERENCES "RedGate".product_categories (category_id) ON DELETE CASCADE
);